# Generated by Django 2.0.3 on 2018-06-01 14:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(choices=[('BS', "Bachelor's degree"), ('MS', "Master's degree"), ('PHD', 'Doctorate'), ('PROF', 'Higher level of Education')], max_length=4, null=True, verbose_name='Level of education'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
    ]
