# Generated by Django 2.0.3 on 2018-04-12 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_time', models.IntegerField()),
                ('task_payment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('task_description', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_content', models.TextField()),
                ('task_uid', models.PositiveIntegerField()),
                ('task_answer_content', models.TextField()),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workinterface.Job')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workinterface.Task'),
        ),
        migrations.AddField(
            model_name='answers',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
