# Generated by Django 2.0.3 on 2018-04-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workinterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='task_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='task_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
