# Generated by Django 2.0.3 on 2018-04-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workinterface', '0002_auto_20180421_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_uid',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
