# Generated by Django 2.0.3 on 2018-04-21 04:03

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workinterface', '0003_auto_20180421_0403'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdcur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_feature', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('task_uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workinterface.Task', to_field='task_uid')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerPreferenceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workermodel',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='workermodel',
            name='needs_update',
            field=models.BooleanField(default=True),
        ),
    ]
