# Generated by Django 2.0.3 on 2018-04-22 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workinterface', '0003_auto_20180421_0403'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdcur', '0002_auto_20180421_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerTaskHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workinterface.Task')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='TaskFeatures',
            new_name='TaskFeaturesModel',
        ),
        migrations.RenameModel(
            old_name='WorkerPreferenceHistory',
            new_name='WorkerPreferenceHistoryModel',
        ),
    ]
