# Generated by Django 2.0.3 on 2018-04-27 13:16

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdcur', '0003_auto_20180422_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerKFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factors', django.contrib.postgres.fields.jsonb.JSONField()),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workermodel',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workerpreferencehistorymodel',
            name='number_of_tasks_done',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workertaskhistorymodel',
            name='successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workertaskhistorymodel',
            name='time_it_took',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workertaskhistorymodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workerpreferencehistorymodel',
            name='preference',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
