# Generated by Django 2.0.3 on 2018-05-02 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcur', '0004_auto_20180427_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertaskhistorymodel',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
