# Generated by Django 2.0.3 on 2018-05-02 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workinterface', '0003_auto_20180421_0403'),
        ('crowdcur', '0005_auto_20180502_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskfeaturesmodel',
            name='task_uid',
        ),
        migrations.AddField(
            model_name='taskfeaturesmodel',
            name='task',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='workinterface.Task'),
            preserve_default=False,
        ),
    ]
