# Generated by Django 2.0.3 on 2018-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcur', '0006_auto_20180502_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceToFeaturesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_name', models.CharField(max_length=200)),
                ('feature_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='workerpreferencehistorymodel',
            name='number_of_tasks_done',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
