# Generated by Django 2.0.3 on 2018-05-03 15:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcur', '0007_auto_20180503_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerpreferencehistorymodel',
            name='number_of_tasks_done',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workerpreferencehistorymodel',
            name='preference',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
